[package]
name = "oasis-runtime-sdk"
version = "0.1.0"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
oasis-core-runtime = { git = "https://github.com/oasisprotocol/oasis-core", rev = "17d2861" }
oasis-runtime-sdk-macros = { path = "../runtime-sdk-macros", optional = true }

# Third party.
serde = { version = "1.0.118", features = ["derive"] }
serde_bytes = "0.11.5"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
sha2 = "0.9.3"
k256 = { version = "0.6.0", features = ["ecdsa"] }
thiserror = "1.0.24"
hex = "0.4.2"
io-context = "0.2.0"
anyhow = "1.0.24"
bech32 = "0.7.2"
num-traits = "0.2.14"
impl-trait-for-tuples = "0.2.1"
base64 = "0.13.0"
once_cell = "1.7.2"
slog = "2.7.0"

[features]
default = ["oasis-runtime-sdk-macros"]
