[package]
name = "oasis-runtime-sdk-macros"
version = "0.1.0"
authors = ["Oasis Protocol Foundation <info@oasisprotocol.org>"]
edition = "2018"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.9"

[dev-dependencies]
syn = { version = "1.0.62", features = ["extra-traits"] }
